commit for issue #262
msandfor/10-Easy-Steps pull request #291
Opened 2020-10-23 20:06 UTC by bruceyboy86

## In this pull request
I have changed the text

#262

2020-10-24 06:34 UTC, msandfor requested changes
Hi @bruceyboy86 , you have replaced the name of the podcast which is "Learn to Code With Me" with the new description "Interviews and advice for learning how to code and building your technology career" which should instead replace the generic comment "Love of Learning". This is line 169 as it should look:

| [Learn To Code With Me](https://learntocodewith.me/podcast/) | Laurence Bradford | 7 | [Interviews and advice for learning how to code and building your technology career | 

Are you able to correct your code and then I'll merge it in?

2020-10-24 21:42 UTC, bruceyboy86 commented
Oops. I'll try again...

2020-10-24 21:47 UTC, bruceyboy86 commented
I've edited the file. I'm not sure if this is a fresh pull request. It seems to have updated the original pull request @msandfor

2020-10-25 14:27 UTC, msandfor approved these changes

2020-10-25 14:28 UTC, merged